// 名称: OPPO签到奖励修改
// 作者: Generated by Assistant
// 描述: 修改 OPPO 签到接口返回的 awardValue 为 9999
// 触发时机: response
// 匹配规则: host=hd.opposhop.cn, path=/api/cn/oapi/marketing/cumulativeSignIn/signIn, method=POST

if ($response.status === 200) {
    try {
        let body = JSON.parse($response.body);
        
        // 修改 awardValue 为 9999
        if (body.data && body.data.awardValue !== undefined) {
            body.data.awardValue = "9999";
            console.log("[OPPO脚本] 已将 awardValue 修改为 9999");
            
            // 重新序列化并更新响应体
            $done({ body: JSON.stringify(body) });
        } else {
            console.log("[OPPO脚本] 响应结构异常，未找到 awardValue 字段");
            $done({});
        }
    } catch (error) {
        console.log("[OPPO脚本] JSON解析或修改失败: " + error);
        $done({});
    }
} else {
    $done({});
}
